package com.example.netapp.entity;

public enum NotificationType {
    APPOINTMENT_CREATED,
    APPOINTMENT_APPROVED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_UPDATED,
    APPOINTMENT_COMPLETED
}
